### ISSUE TITLE
Support external File reference in DockerRequirement `dockerFile`

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#338] opened 2016-11-08 16:34 UTC
The `dockerFile` field currently is a string.  Could make it a File object referencing the Dockerfile which can include secondaryFiles.

**Comment by mr-c** [comment] 2018-01-24 10:48
Duplicate of https://github.com/common-workflow-language/common-workflow-language/issues/294

**Closed by mr-c** 2018-01-24 10:48 UTC
