### ISSUE TITLE
InputRecordSchema needs a field "name"

### ISSUE THREAD

**Issue by wgerlach** [common-workflow-language/common-workflow-language#572] opened 2017-12-12 19:20 UTC
In this compliance test tool there is field "name" in a InputRecordSchema object:
https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/tmap-tool.cwl#L90

But, in the specification it is not defined:
http://www.commonwl.org/v1.0/CommandLineTool.html#InputRecordSchema

Is the specification missing this field ?

**Comment by mr-c** [comment] 2017-12-15 14:23
Hello @wgerlach 

Yes, this is an oversight in v1.0.3

**Comment by mr-c** [comment] 2017-12-15 14:23
Thank you for reporting this :-)

**Comment by mr-c** [comment] 2018-01-24 09:27
Duplicate of https://github.com/common-workflow-language/common-workflow-language/issues/216

**Closed by mr-c** 2018-01-24 09:27 UTC
Labels: spec change
