### ISSUE TITLE
`optional_file: null` is not checked.

### ISSUE THREAD

**Issue by manabuishii** [common-workflow-language/common-workflow-language#744] opened 2018-07-19 01:54 UTC
conformance test 67
expects result has `optional_file: null` but I think this is not check.

```
- tool: v1.0/optional-output.cwl
  job: v1.0/cat-job.json
  output:
    optional_file: null
    output_file:
        location: output.txt
        size: 13
        class: "File"
        checksum: "sha1$47a013e660d408619d894b20806b1d5086aab03b"
  label: output_secondaryfile_optional
  id: 67
  doc: |
    Test optional output file and optional secondaryFile on output.
  tags: [ docker, command_line_tool ]
```

Because the following result passed conformance test 67.
This result does not have `optional_file: null`.

```
{
	"output_file": {
		"basename": "output.txt",
		"checksum": "sha1$47a013e660d408619d894b20806b1d5086aab03b",
		"class": "File",
		"location": "file:///tmp/111/output.txt",
		"path": "/tmp/111/output.txt",
		"size": 13
	}
}
```

**Comment by tom-tan** [comment] 2018-07-19 02:18
Optional input and output parameters can be omitted from input and output object, respectively.

The problem is that such a behavior is not documented in the specification. IMO it should be clarified.

**Comment by tom-tan** [comment] 2018-12-13 02:15
I close this issue because it is duplicated with #810.

**Closed by tom-tan** 2018-12-13 02:15 UTC
