### ISSUE TITLE
Installation fails since 1.0.20150318015654

### ISSUE THREAD

**Issue by hannes-ucsc** [common-workflow-language/common-workflow-language#28] opened 2015-03-23 18:27 UTC
Steps to reproduce:

```
virtualenv FOO
FOO/bin/pip install cwltool
FOO/bin/cwltool
```
 and I get 

```
Traceback (most recent call last):
  File "FOO/bin/cwltool", line 9, in <module>
    load_entry_point('cwltool==1.0.20150318015654', 'console_scripts', 'cwltool')()
  File "/Users/hannes/FOO/lib/python2.7/site-packages/pkg_resources/__init__.py", line 474, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/hannes/FOO/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2582, in load_entry_point
    return ep.load()
  File "/Users/hannes/FOO/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2265, in load
    return self._load()
  File "/Users/hannes/FOO/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2268, in _load
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/hannes/FOO/lib/python2.7/site-packages/cwltool/main.py", line 3, in <module>
    import draft1tool
  File "/Users/hannes/FOO/lib/python2.7/site-packages/cwltool/draft1tool.py", line 23, in <module>
    with open(jsonschemapath) as f:
IOError: [Errno 2] No such file or directory: '/Users/hannes/FOO/lib/python2.7/site-packages/cwltool/schemas/draft-1/json-schema-draft-04.json'
```

**Comment by seandavi** [comment] 2015-03-23 18:34
Same thing here.

**Comment by jvivian** [comment] 2015-03-23 18:48
I had to go back to this commit:  **f1cfee160a62f7ecceed85853e6acfa457b9a015** in order to remove the error (not a solution as it breaks other functionality)

**Comment by seandavi** [comment] 2015-03-23 18:51
A clone at this commit 6dc4889a1 seems to work for me?

**Comment by jvivian** [comment] 2015-03-23 19:09
Can confirm seandavi's results, although actually running cwltool on an example tool/job is giving me subprocess.py errors. 

    cwltool wc2-tool.cwl wc-job.json 

gives me

```
Traceback (most recent call last):
  File "/Users/Jvivian/anaconda/bin/cwltool", line 9, in <module>
    load_entry_point('cwltool==1.0.20150318015654', 'console_scripts', 'cwltool')()
  File "/Users/Jvivian/anaconda/lib/python2.7/site-packages/cwltool-1.0.20150318015654-py2.7.egg/cwltool/main.py", line 72, in main
    (outdir, runjob) = job.run(dry_run=args.dry_run, pull_image=(not args.no_pull), outdir=args.outdir)
  File "/Users/Jvivian/anaconda/lib/python2.7/site-packages/cwltool-1.0.20150318015654-py2.7.egg/cwltool/job.py", line 126, in run
    return (outdir, self.collect_outputs(outdir))
  File "/Users/Jvivian/anaconda/lib/python2.7/site-packages/cwltool-1.0.20150318015654-py2.7.egg/cwltool/draft2tool.py", line 324, in collect_output_ports
    ret = {port["id"][1:]: self.collect_output(port, builder, outdir) for port in ports}
  File "/Users/Jvivian/anaconda/lib/python2.7/site-packages/cwltool-1.0.20150318015654-py2.7.egg/cwltool/draft2tool.py", line 324, in <dictcomp>
    ret = {port["id"][1:]: self.collect_output(port, builder, outdir) for port in ports}
  File "/Users/Jvivian/anaconda/lib/python2.7/site-packages/cwltool-1.0.20150318015654-py2.7.egg/cwltool/draft2tool.py", line 357, in collect_output
    r = builder.do_eval(binding["valueFrom"], r)
  File "/Users/Jvivian/anaconda/lib/python2.7/site-packages/cwltool-1.0.20150318015654-py2.7.egg/cwltool/draft2tool.py", line 39, in do_eval
    return self.jseval(ex["value"], context)
  File "/Users/Jvivian/anaconda/lib/python2.7/site-packages/cwltool-1.0.20150318015654-py2.7.egg/cwltool/draft2tool.py", line 33, in jseval
    return sandboxjs.execjs(exp, "var $job = %s; var $self = %s; %s" % (json.dumps(self.job), json.dumps(context), self.jslib))
  File "/Users/Jvivian/anaconda/lib/python2.7/site-packages/cwltool-1.0.20150318015654-py2.7.egg/cwltool/sandboxjs.py", line 9, in execjs
    nodejs = subprocess.Popen(["nodejs"], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/Users/Jvivian/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/Jvivian/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by seandavi** [comment] 2015-03-23 19:32
[off-topic] Is there a formal testing process/CI process in place?  Is it worth opening an issue to create one?

**Comment by tetron** [comment] 2015-03-23 20:19
I believe the problem is that package-data in setup.py isn't being included.  I will look at that tomorrow.

Regarding setting up a CI/testing server, yes, please create a separate issue for that.

**Comment by hannes-ucsc** [comment] 2015-03-23 23:39
Also, would it be possible to tag releases in git when they are pushed to PyPi?

**Comment by tetron** [comment] 2015-03-24 01:42
The packages are already built and pushed automatically.  The timestamp on the package version is the timestamp of the git commit.

I believe I fixed the problem of schemas not being included in the source dist package, unfortunately, I seem to be getting different results running "python setup.py sdist" on my workstation (the schema files are included as intended) compared to the CI server which actually builds and uploads to PyPi (where the schema files are being excluded).  I will investigate further.

**Comment by hannes-ucsc** [comment] 2015-03-24 01:51
Yeah, the package name contains the commit but I was referring to Git tags. Isn't it pretty much standard these days to tag your releases in git? It certainly would have made it easier for us to revert to the previous release via the ```git clone && git checkout && easy_install .``` procedure if only the previous release been tagged in git.

**Comment by tetron** [comment] 2015-03-24 02:20
Hi @hannes-ucsc, what I mean is that with rolling release/automatic package upload from master, if every package were tagged automatically you would end up with git tags dropdown with 132 entries, so you don't get any benefit from browsing tags compared to just browsing commit history.

At some point we will probably start making actual stable releases with manually assigned semantic versions and moving towards a more stable branch/merge development flow, but we are not quite there yet.

I'm happy to discuss this further if you want to open a ticket specifically about versioning, or take it to wider community on the mailing list.

**Comment by tetron** [comment] 2015-03-24 21:11
I think this is fixed as of 3bb8b95 (cwltool-1.0.20150324203244), can you verify?

**Comment by hannes-ucsc** [comment] 2015-03-24 21:36
Verified.

**Comment by hannes-ucsc** [comment] 2015-03-24 22:24
... for cwltool-1.0.20150324211351 as well as cwltool-1.0.20150324203244

**Closed** 2015-03-25 13:00 UTC
