### ISSUE TITLE
new conformance test needed for boolean input values

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#547] opened 2017-11-23 03:06 UTC
https://github.com/rabix/bunny/issues/288

**Comment by anton-khodak** [comment] 2018-01-27 11:33
Duplicate of https://github.com/common-workflow-language/common-workflow-language/issues/604?

**Comment by anton-khodak** [comment] 2018-01-30 06:12
Closed in https://github.com/common-workflow-language/common-workflow-language/pull/610

**Closed by anton-khodak** 2018-01-30 06:12 UTC
Labels: conformance test
