### ISSUE TITLE
Is `name` allowed in `requirements[i].types[i]`?

### ISSUE THREAD

**Issue by otiai10** [common-workflow-language/common-workflow-language#517] opened 2017-09-13 06:35 UTC
As reading [this document](http://www.commonwl.org/v1.0/CommandLineTool.html#SchemaDefRequirement) about `SchemaDefRequirement`,
types should be `array<InputRecordSchema | InputEnumSchema | InputArraySchema>`.

On the other hand, [these two props](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/tmap-tool.cwl#L90-L91) are belonging to an element of `types` field.

It means either InputRecordSchema, InputEnumSchema and InputArraySchema must have `name` field.

- http://www.commonwl.org/v1.0/CommandLineTool.html#InputRecordSchema
- http://www.commonwl.org/v1.0/CommandLineTool.html#InputEnumSchema
- http://www.commonwl.org/v1.0/CommandLineTool.html#InputArraySchema

neither of them has `name` field.

Which is correct, docs or examples? or am I wrong?
 
------

(just I guess it was some typo that should have written in one of `fields` elements)

**Comment by otiai10** [comment] 2017-09-13 06:49
Similar problem can be seen also here
https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/tmap-tool.cwl#L61

**Comment by mr-c** [comment] 2018-01-24 11:30
Thank you @otiai10 for your report, this appears to be a duplicate of https://github.com/common-workflow-language/common-workflow-language/issues/216

**Closed by mr-c** 2018-01-24 11:30 UTC
