### ISSUE TITLE
Unable to run cwlsite.cwl cwlsite-job.json

### ISSUE THREAD

**Issue by thomasyu888** [common-workflow-language/common-workflow-language#194] opened 2016-03-24 21:05 UTC
When I clone the userguide2 branch and try to run:
```cd site && cwl-runner cwlsite.cwl cwlsite-job.json && open draft-3/UserGuide.html```

This is the error message:
```
$ cwl-runner cwlsite.cwl cwlsite-job.json 
/usr/local/bin/cwl-runner 1.0.20160308152645
Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cwltool/workflow.py", line 472, in job
    **kwargs):
  File "/usr/local/lib/python2.7/site-packages/cwltool/draft2tool.py", line 173, in job
    adjustFileObjs(builder.files, _check_adjust)
  File "/usr/local/lib/python2.7/site-packages/cwltool/process.py", line 154, in adjustFileObjs
    adjustFileObjs(d, op)
  File "/usr/local/lib/python2.7/site-packages/cwltool/process.py", line 151, in adjustFileObjs
    adjustFileObjs(rec[d], op)
  File "/usr/local/lib/python2.7/site-packages/cwltool/process.py", line 154, in adjustFileObjs
    adjustFileObjs(d, op)
  File "/usr/local/lib/python2.7/site-packages/cwltool/process.py", line 151, in adjustFileObjs
    adjustFileObjs(rec[d], op)
  File "/usr/local/lib/python2.7/site-packages/cwltool/process.py", line 154, in adjustFileObjs
    adjustFileObjs(d, op)
  File "/usr/local/lib/python2.7/site-packages/cwltool/process.py", line 149, in adjustFileObjs
    op(rec)
  File "/usr/local/lib/python2.7/site-packages/cwltool/draft2tool.py", line 169, in _check_adjust
    f["path"] = builder.pathmapper.mapper(f["path"])[1]
  File "/usr/local/lib/python2.7/site-packages/cwltool/pathmapper.py", line 26, in mapper
    return self._pathmap[src]
KeyError: 'file:///Users/thomasyu/sandbox/common-workflow-language/draft-3/concepts.md'
Workflow error, try again with --debug for more information:
  'file:///Users/thomasyu/sandbox/common-workflow-language/draft-3/concepts.md'
```

I ran it with debug:
```
$ cwl-runner --debug cwlsite.cwl cwlsite-job.json 
/usr/local/bin/cwl-runner 1.0.20160308152645
[workflow cwlsite.cwl] initialized from file:///Users/thomasyu/sandbox/common-workflow-language/site/cwlsite.cwl
[workflow cwlsite.cwl] starting
[step 4575498128] starting job step file:///Users/thomasyu/sandbox/common-workflow-language/site/cwlsite.cwl#docs of workflow 4565231248
Exception on step 'docs'
Workflow error, try again with --debug for more information:
  Error validating input record, could not validate field `brand` because
  the value `{'class': 'File',
   'path': 'file:///Users/thomasyu/sandbox/common-workflow-language/site/CWL-Logo-Header.png'}` is not string
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cwltool/main.py", line 545, in main
    select_resources=selectResources
  File "/usr/local/lib/python2.7/site-packages/cwltool/main.py", line 160, in single_job_executor
    for r in jobiter:
  File "/usr/local/lib/python2.7/site-packages/cwltool/workflow.py", line 370, in job
    for w in wj.job(builder.job, basedir, output_callback, **kwargs):
  File "/usr/local/lib/python2.7/site-packages/cwltool/workflow.py", line 287, in job
    for newjob in step.iterable:
  File "/usr/local/lib/python2.7/site-packages/cwltool/workflow.py", line 243, in try_make_job
    for j in jobs:
  File "/usr/local/lib/python2.7/site-packages/cwltool/workflow.py", line 528, in dotproduct_scatter
    for j in process.job(jo, basedir, functools.partial(rc.receive_scatter_output, n), **kwargs):
  File "/usr/local/lib/python2.7/site-packages/cwltool/workflow.py", line 145, in job
    for j in self.step.job(joborder, basedir, output_callback, **kwargs):
  File "/usr/local/lib/python2.7/site-packages/cwltool/workflow.py", line 472, in job
    **kwargs):
  File "/usr/local/lib/python2.7/site-packages/cwltool/draft2tool.py", line 100, in job
    builder = self._init_job(joborder, input_basedir, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/cwltool/process.py", line 276, in _init_job
    raise WorkflowException("Error validating input record, " + str(e))
WorkflowException: Error validating input record, could not validate field `brand` because
  the value `{'class': 'File',
   'path': 'file:///Users/thomasyu/sandbox/common-workflow-language/site/CWL-Logo-Header.png'}` is not string
```

**Comment by tetron** [comment] 2016-03-25 15:12
Hi @thomasyu888, I've updated the branch, would you like to try again?  Also consider updating cwltool and updating the container used by the site generator with "docker pull commonworkflowlanguage/cwltool_module".

**Comment by thomasyu888** [comment] 2016-03-25 17:34
Thank you @tetron.  I still get an error:
```
Exception on step 'docs'
Workflow error, try again with --debug for more information:
  Missing input file [Errno 2] No such file or directory: '/home/peter/work/common-workflow-language/draft-3/examples/example-1st.cwl'
```

**Comment by tetron** [comment] 2016-03-25 20:52
Oops, I messed up the input files paths.  Will fix.

On March 25, 2016 1:35:01 PM EDT, Thomas Yu <notifications@github.com> wrote:
>Thank you @tetron.  I still get an error:
>```
>Exception on step 'docs'
>Workflow error, try again with --debug for more information:
>Missing input file [Errno 2] No such file or directory:
>'/home/peter/work/common-workflow-language/draft-3/examples/example-1st.cwl'
>```
>
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/common-workflow-language/common-workflow-language/issues/194#issuecomment-201380793

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by thomasyu888** [comment] 2016-03-30 23:09
I get this error now:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/schema_salad/makedoc.py", line 462, in <module>
  File "build/bdist.linux-x86_64/egg/schema_salad/ref_resolver.py", line 267, in resolve_ref
  File "build/bdist.linux-x86_64/egg/schema_salad/ref_resolver.py", line 382, in resolve_all
  File "build/bdist.linux-x86_64/egg/schema_salad/ref_resolver.py", line 361, in resolve_all
  File "build/bdist.linux-x86_64/egg/schema_salad/ref_resolver.py", line 382, in resolve_all
  File "build/bdist.linux-x86_64/egg/schema_salad/ref_resolver.py", line 295, in resolve_all
  File "build/bdist.linux-x86_64/egg/schema_salad/ref_resolver.py", line 253, in resolve_ref
  File "build/bdist.linux-x86_64/egg/schema_salad/ref_resolver.py", line 418, in fetch_text
RuntimeError: Error reading file:///var/lib/cwl/job761237227_draft-3/examples/example-docker.cwl [Errno 2] No such file or directory: '/var/lib/cwl/job761237227_draft-3/examples/example-docker.cwl'
[job docs_6] completed permanentFail
[step docs] completion status is permanentFail
Workflow error, try again with --debug for more information:
  Output for workflow not available
```

**Comment by thomasyu888** [comment] 2016-03-30 23:29
I ran it again and it worked, however now it says:
```
[step rdfs] completion status is success
Workflow error, try again with --debug for more information:
  Output for workflow not available
```
When I go to draft-3, Userguide.html does not exist.

**Comment by mr-c** [comment] 2016-03-31 09:24
@thomasyu888 Thanks for the follow up. I am able to reproduce the error and I will have a fix for you shortly

**Comment by mr-c** [comment] 2016-03-31 09:41
@thomasyu888 I've pushed a fix to the userguide2 branch.
@tetron In 323210675300000129821030 I had to comment out the inclusion of `examples/example-env.cwl` as it doesn't exist yet. Mind checking that in? Thanks for writing this!

**Comment by mr-c** [comment] 2016-04-12 11:04
Thank you @tetron for checking in `examples/example-env.cwl`.

@thomasyu888 Looks like this is fixed. Thanks again for reporting this.

**Closed by mr-c** 2016-04-12 11:04 UTC

**Comment by thomasyu888** [comment] 2016-04-18 22:21
@tetron @mr-c  Thanks for the fix! Works well!
