### ISSUE TITLE
Is `name` allowed in `type`?

### ISSUE THREAD

**Issue by manabuishii** [common-workflow-language/common-workflow-language#519] opened 2017-09-13 15:48 UTC
In this file

https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/record-output.cwl#L8

`type` has `name` field.
Is this allowed ?
I can not find document about this.

**Comment by mr-c** [comment] 2017-12-05 14:07
Yes, it is missing from the `RecordSchema` and `EnumSchema` but will be clarified by v1.1

**Comment by mr-c** [comment] 2018-01-24 09:27
Duplicate of https://github.com/common-workflow-language/common-workflow-language/issues/216

**Closed by mr-c** 2018-01-24 09:27 UTC
Labels: spec change
