### ISSUE TITLE
Move secondaryFiles on inputs.

### ISSUE THREAD

**Issue by jmchilton** [common-workflow-language/common-workflow-language#161] opened 2015-11-04 22:22 UTC
Needs to be with the input and not with the inputBinding.

**Comment by mr-c** [comment] 2015-12-09 15:31
@jmchilton Can this wait for Draft 4?

**Comment by jmchilton** [comment] 2015-12-09 15:32
I made this issue based on discussions others were having, I don't even really remember what it means :worried:.

**Comment by mr-c** [comment] 2015-12-09 15:33
Heh.

Looks to be related to #127

**Comment by ntijanic** [comment] 2015-12-09 18:26
Yes - if proposed design makes it to draft-3, we can close this as well.

The issue is that the `secondaryFiles` is currently nested under `inputBinding` and should just be a property of the input itself since non-bound inputs can have required secondary files.

**Comment by ntijanic** [comment] 2015-12-09 18:45
Closing - can be considered duplicate of #127.

**Closed by ntijanic** 2015-12-09 18:45 UTC
