### ISSUE TITLE
Localization for doc/label strings in a CWL document

### ISSUE THREAD

**Issue by kghosesbg** [common-workflow-language/common-workflow-language#751] opened 2018-07-27 16:03 UTC
We have client(s) who have a requirement for workflows with documentation in a localized language. Right now the only way to do this seems to be to fork the CWL document and rewrite the `doc` and `label` sections in the localized language. Is there another way? If not could we implement a localization system for these fields that would allow the same document to carry or link to multiple versions of the same `doc` or `label` in different localizations?

**Comment by tetron** [comment] 2018-07-27 16:05
Duplicate of #546 (will close this one, please review the discussion / proposal on that ticket)

**Closed by tetron** 2018-07-27 16:05 UTC

**Comment by kghosesbg** [comment] 2018-07-27 18:38
Thanks @tetron . I did a search for localization and didn't find anything 😄
